language: go
go:
  - "1.11"
services:
  - docker

install:
  - docker pull koalaman/shellcheck
  - go get -u golang.org/x/lint/golint

before_script:
  - go vet ./...
  - go build
  - go test -run xxxx ./...
  - make testenv

script:
  # - docker run -v $(pwd):/mnt koalaman/shellcheck **/*.sh(e[' [[ ! `echo "$REPLY" | grep "vendor/" ` ]]'])
  - go fmt ./...
  - golint $(go list ./... | grep -v /vendor/) # golint doesn't ignore vendor
  - go test -race -short -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: 
  email: false 
